#!/bin/bash
#
# Made with love by Colm3na|N0∞D0|wiπΞl
#
# Script para importar wallet
#
# Comando:
# gaiacli keys add --recover <nombreWallet>
#

echo "¿Qué nombre quieres ponerle a la wallet?"
read -r name

gaiacli keys add --recover "$name"