#!/bin/bash
#
# Made with love by Colm3na|N0∞D0|wiπΞl
#
# Script para ver el balance de una wallet
#
# gaiacli tx send <destination_cosmos> 10faucetToken \
# --chain-id=<chain_id> \
# --from=<key_name> \
#
# Variables:
chain_id=$(curl -s http://localhost:26657/status | jq -r '.result.node_info.network')

gaiacli keys list

echo  "¿Qué wallet quieres usar?(puedes usar su nombre)"
read -r wallet

echo "¿A qué wallet quieres enviar?"
read -r destiny

echo "¿Qué cantidad?"
read -r amount

gaiacli tx send "${destiny}" "${amount}" --chain-id="${chain_id}" --from="${wallet}" --fees=5000uatom -y
