#!/bin/bash
#
# Made with love by Colm3na|N0∞D0|wiπΞl
#
# Script para ver los validadores
#
# Comando:
# gaiacli query tendermint-validator-set --trust-node=true
#
gaiacli query tendermint-validator-set --trust-node=true