#!/bin/bash
#
# Made with love by Colm3na|N0∞D0|wiπΞl
#
# Script para delegar fondos, sustituir las variables
#
# Comando:
# gaiacli tx staking delegate <validatorAddress> <amountToBond> --from <delegatorKeyName> --gas auto --gas-prices <gasPrice> --fees 1000photino
#
##Variables:
#
chain_id=$(curl -s http://localhost:26657/status | jq -r '.result.node_info.network')

gaiacli keys list

echo "¿Qué wallet quieres usar?(cosmos123...)"
read -r wallet

echo "¿Qué cantidad quieres delegar?"
read -r amount

echo "¿A qué validador has elegido?(cosmosvaloper...)"
read -r delegator

gaiacli tx staking delegate "${delegator}" "${amount}"muon --from="${wallet}" --chain-id="${chain_id}" --fees=10000photino -y
