#!/bin/bash
#
# Script para delegar fondos, sustituir las variables
#
# Comando:
# gaiacli tx staking delegate <validatorAddress> <amountToBond> --from <delegatorKeyName> --gas auto --gas-prices <gasPrice> --fees 1000photino
#
##Variables:
#
chain_id=`curl -s http://localhost:26657/status | jq -r '.result.node_info.network'`

gaiacli keys list

echo "¿Qué wallet quieres usar?"
read wallet

echo "¿Qué cantidad quieres delegar?"
read amount

echo "A qué wallet quieres delegarlo?"
read delegator

echo "gaiacli tx staking delegate $delegator $amount muon --from $wallet --gas auto --chain-id $chain_id --fees 10000photino"
