#!/bin/bash
#
# Script para ver el balance de una wallet
#
# Comando:
# gaiacli tx staking delegate <validatorAddress> <amountToBond> --from <delegatorAddress> --gas auto --gas-prices <gasPrice> --generate-only > unsignedTX.json
#