#!/bin/bash
#
# Script para hacer unbound
#
# Comando:
# gaiacli keys add <nombreWallet>
#
# gaiacli tx staking unbond \
#   --validator=<account_cosmosval> \
#   --shares-fraction=0.5 \
#   --from=<key_name> \
#   --chain-id=<chain_id>
